-- TennisLedger database schema for Supabase
-- Run this file once in: Supabase Dashboard -> SQL Editor -> New query
--
-- Security model:
--   * anon: no ledger data access
--   * authenticated non-admin: can only check whether their own UID exists in admins
--   * authenticated admin: can read/write ledger data
--   * clients can read tables, but every write must go through a controlled RPC
--   * balance updates and transaction rows are committed atomically

begin;

create schema if not exists private;

-- ============================================================
-- Tables
-- ============================================================

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.ledgers (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists ledgers_active_name_unique
  on public.ledgers (lower(trim(name)))
  where deleted_at is null;

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  ledger_id bigint not null references public.ledgers(id),
  name text not null check (char_length(trim(name)) between 1 and 60),
  balance numeric(14, 2) not null default 0,
  created_at timestamptz not null default now(),
  constraint members_ledger_id_name_key unique (ledger_id, name)
);

create index if not exists members_ledger_id_idx
  on public.members (ledger_id);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  ledger_id bigint not null references public.ledgers(id),
  member_id bigint references public.members(id),
  member_name text not null,
  amount numeric(14, 2) not null,
  balance_before numeric(14, 2) not null,
  balance_after numeric(14, 2) not null,
  note text check (note is null or char_length(note) <= 200),
  operator_id uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint transactions_balance_math_check
    check (balance_after = balance_before + amount)
);

-- `create table if not exists` does not add new constraints to an older install.
-- Keep this migration block so re-running the file also upgrades that install.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'transactions_balance_math_check'
      and conrelid = 'public.transactions'::regclass
  ) then
    alter table public.transactions
      add constraint transactions_balance_math_check
      check (balance_after = balance_before + amount)
      not valid;
  end if;
end;
$$;

create index if not exists transactions_ledger_created_idx
  on public.transactions (ledger_id, created_at desc);

create index if not exists transactions_ledger_id_desc_idx
  on public.transactions (ledger_id, id desc);

-- ============================================================
-- Admin helper used by RLS.
-- Kept outside the exposed public schema because it is SECURITY DEFINER.
-- ============================================================

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on schema private from public, anon, authenticated;
revoke all on function private.is_admin() from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;

-- ============================================================
-- RLS
-- ============================================================

alter table public.admins enable row level security;
alter table public.ledgers enable row level security;
alter table public.members enable row level security;
alter table public.transactions enable row level security;

-- Re-running this schema should be safe.
drop policy if exists "users can read own admin row" on public.admins;
create policy "users can read own admin row"
on public.admins
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "admins can read ledgers" on public.ledgers;
create policy "admins can read ledgers"
on public.ledgers
for select
to authenticated
using ((select private.is_admin()));

-- No INSERT/UPDATE/DELETE policies are created. Browser writes are deliberately
-- limited to the SECURITY DEFINER RPC functions below.
drop policy if exists "admins can insert ledgers" on public.ledgers;
drop policy if exists "admins can update ledgers" on public.ledgers;

drop policy if exists "admins can read members" on public.members;
create policy "admins can read members"
on public.members
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "admins can insert members" on public.members;
drop policy if exists "admins can update members" on public.members;

drop policy if exists "admins can read transactions" on public.transactions;
create policy "admins can read transactions"
on public.transactions
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "admins can insert transactions" on public.transactions;

-- ============================================================
-- RPC functions
-- SECURITY DEFINER is intentional: browser roles have no direct table-write
-- privileges, so these narrowly scoped functions are the only write path.
-- Every function checks private.is_admin(), fixes search_path, and each call runs
-- in one PostgreSQL transaction.
-- ============================================================

create or replace function public.create_ledger(p_name text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := trim(p_name);
  v_id bigint;
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  if v_name is null or char_length(v_name) = 0 or char_length(v_name) > 60 then
    raise exception 'Ledger name must be between 1 and 60 characters';
  end if;

  insert into public.ledgers(name)
  values (v_name)
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.delete_ledger(p_ledger_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  update public.ledgers
  set deleted_at = now()
  where id = p_ledger_id
    and deleted_at is null;

  if not found then
    raise exception 'Ledger does not exist';
  end if;
end;
$$;

create or replace function public.add_member(
  p_ledger_id bigint,
  p_name text,
  p_initial_balance numeric
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := trim(p_name);
  v_balance numeric(14, 2) := round(coalesce(p_initial_balance, 0)::numeric, 2);
  v_member_id bigint;
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  if v_name is null or char_length(v_name) = 0 or char_length(v_name) > 60 then
    raise exception 'Member name must be between 1 and 60 characters';
  end if;

  if v_balance = 'NaN'::numeric then
    raise exception 'Initial balance must be a finite number';
  end if;

  -- Hold a shared row lock until the member and its initial transaction commit.
  -- A concurrent soft-delete must wait and cannot interleave with this write.
  perform 1
  from public.ledgers
  where id = p_ledger_id
    and deleted_at is null
  for share;

  if not found then
    raise exception 'Ledger does not exist';
  end if;

  insert into public.members(ledger_id, name, balance)
  values (p_ledger_id, v_name, v_balance)
  returning id into v_member_id;

  insert into public.transactions(
    ledger_id,
    member_id,
    member_name,
    amount,
    balance_before,
    balance_after,
    note,
    operator_id
  ) values (
    p_ledger_id,
    v_member_id,
    v_name,
    v_balance,
    0,
    v_balance,
    '初始余额',
    (select auth.uid())
  );

  return v_member_id;
end;
$$;

create or replace function public.adjust_balance(
  p_member_id bigint,
  p_amount numeric,
  p_note text default null
)
returns numeric
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ledger_id bigint;
  v_member_name text;
  v_before numeric(14, 2);
  v_amount numeric(14, 2) := round(p_amount::numeric, 2);
  v_after numeric(14, 2);
  v_note text := nullif(trim(p_note), '');
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  if v_amount is null or v_amount = 0 or v_amount = 'NaN'::numeric then
    raise exception 'Amount must be a non-zero number';
  end if;

  if v_note is not null and char_length(v_note) > 200 then
    raise exception 'Note must be 200 characters or fewer';
  end if;

  -- Discover the parent first, then always lock ledger -> member. The shared
  -- ledger lock prevents a concurrent soft-delete while this operation commits.
  select m.ledger_id
  into v_ledger_id
  from public.members as m
  where m.id = p_member_id;

  if not found then
    raise exception 'Member does not exist';
  end if;

  perform 1
  from public.ledgers
  where id = v_ledger_id
    and deleted_at is null
  for share;

  if not found then
    raise exception 'Ledger does not exist';
  end if;

  select m.name, m.balance
  into v_member_name, v_before
  from public.members as m
  where m.id = p_member_id
    and m.ledger_id = v_ledger_id
  for update;

  if not found then
    raise exception 'Member does not exist';
  end if;

  v_after := v_before + v_amount;

  update public.members
  set balance = v_after
  where id = p_member_id;

  insert into public.transactions(
    ledger_id,
    member_id,
    member_name,
    amount,
    balance_before,
    balance_after,
    note,
    operator_id
  ) values (
    v_ledger_id,
    p_member_id,
    v_member_name,
    v_amount,
    v_before,
    v_after,
    v_note,
    (select auth.uid())
  );

  return v_after;
end;
$$;

-- ============================================================
-- Data API privileges
-- ============================================================

revoke all on table public.admins from public, anon, authenticated;
revoke all on table public.ledgers from public, anon, authenticated;
revoke all on table public.members from public, anon, authenticated;
revoke all on table public.transactions from public, anon, authenticated;

-- A signed-in user can only see their own row because of the admins RLS policy.
grant select on table public.admins to authenticated;

-- RLS blocks every non-admin account from these reads. No browser role receives
-- INSERT/UPDATE/DELETE: writes can only happen inside the RPC functions below.
grant select on table public.ledgers to authenticated;
grant select on table public.members to authenticated;
grant select on table public.transactions to authenticated;

revoke all on sequence
  public.ledgers_id_seq,
  public.members_id_seq,
  public.transactions_id_seq
from public, anon, authenticated;

revoke execute on function public.create_ledger(text) from public, anon, authenticated;
revoke execute on function public.delete_ledger(bigint) from public, anon, authenticated;
revoke execute on function public.add_member(bigint, text, numeric) from public, anon, authenticated;
revoke execute on function public.adjust_balance(bigint, numeric, text) from public, anon, authenticated;

grant execute on function public.create_ledger(text) to authenticated;
grant execute on function public.delete_ledger(bigint) to authenticated;
grant execute on function public.add_member(bigint, text, numeric) to authenticated;
grant execute on function public.adjust_balance(bigint, numeric, text) to authenticated;

commit;

-- Existing installs receive the balance-math constraint as NOT VALID so old,
-- manually edited history cannot roll back the security upgrade above. After
-- auditing/fixing legacy rows, validate it separately with:
--
-- alter table public.transactions
--   validate constraint transactions_balance_math_check;

-- ============================================================
-- AFTER running this schema:
-- 1. Create a user in Supabase Dashboard -> Authentication -> Users.
-- 2. Copy that user's UUID.
-- 3. Run the following separately, replacing the UUID:
--
-- insert into public.admins(user_id)
-- values ('00000000-0000-0000-0000-000000000000');
-- ============================================================
