-- TennisLedger database schema for Supabase
-- Run this file once in: Supabase Dashboard -> SQL Editor -> New query
--
-- Security model:
--   * anon: no ledger data access
--   * authenticated non-admin: can only check whether their own UID exists in admins
--   * authenticated admin: can read/write ledger data
--   * transaction rows are append-only from the client side

begin;

create schema if not exists private;

-- ============================================================
-- Tables
-- ============================================================

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.ledgers (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists ledgers_active_name_unique
  on public.ledgers (lower(trim(name)))
  where deleted_at is null;

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  ledger_id bigint not null references public.ledgers(id),
  name text not null check (char_length(trim(name)) between 1 and 60),
  balance numeric(14, 2) not null default 0,
  created_at timestamptz not null default now(),
  constraint members_ledger_id_name_key unique (ledger_id, name)
);

create index if not exists members_ledger_id_idx
  on public.members (ledger_id);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  ledger_id bigint not null references public.ledgers(id),
  member_id bigint references public.members(id),
  member_name text not null,
  amount numeric(14, 2) not null,
  balance_before numeric(14, 2) not null,
  balance_after numeric(14, 2) not null,
  note text check (note is null or char_length(note) <= 200),
  operator_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists transactions_ledger_created_idx
  on public.transactions (ledger_id, created_at desc);

-- ============================================================
-- Admin helper used by RLS.
-- Kept outside the exposed public schema because it is SECURITY DEFINER.
-- ============================================================

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function private.is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;

-- ============================================================
-- RLS
-- ============================================================

alter table public.admins enable row level security;
alter table public.ledgers enable row level security;
alter table public.members enable row level security;
alter table public.transactions enable row level security;

-- Re-running this schema should be safe.
drop policy if exists "users can read own admin row" on public.admins;
create policy "users can read own admin row"
on public.admins
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "admins can read ledgers" on public.ledgers;
create policy "admins can read ledgers"
on public.ledgers
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "admins can insert ledgers" on public.ledgers;
create policy "admins can insert ledgers"
on public.ledgers
for insert
to authenticated
with check ((select private.is_admin()));

drop policy if exists "admins can update ledgers" on public.ledgers;
create policy "admins can update ledgers"
on public.ledgers
for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "admins can read members" on public.members;
create policy "admins can read members"
on public.members
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "admins can insert members" on public.members;
create policy "admins can insert members"
on public.members
for insert
to authenticated
with check ((select private.is_admin()));

drop policy if exists "admins can update members" on public.members;
create policy "admins can update members"
on public.members
for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "admins can read transactions" on public.transactions;
create policy "admins can read transactions"
on public.transactions
for select
to authenticated
using ((select private.is_admin()));

drop policy if exists "admins can insert transactions" on public.transactions;
create policy "admins can insert transactions"
on public.transactions
for insert
to authenticated
with check (
  (select private.is_admin())
  and operator_id = (select auth.uid())
);

-- ============================================================
-- RPC functions
-- SECURITY INVOKER is intentional: all writes still pass through RLS.
-- Each RPC call runs in one PostgreSQL transaction.
-- ============================================================

create or replace function public.create_ledger(p_name text)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_name text := trim(p_name);
  v_id bigint;
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  if v_name is null or char_length(v_name) = 0 or char_length(v_name) > 60 then
    raise exception 'Ledger name must be between 1 and 60 characters';
  end if;

  insert into public.ledgers(name)
  values (v_name)
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.delete_ledger(p_ledger_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  update public.ledgers
  set deleted_at = now()
  where id = p_ledger_id
    and deleted_at is null;

  if not found then
    raise exception 'Ledger does not exist';
  end if;
end;
$$;

create or replace function public.add_member(
  p_ledger_id bigint,
  p_name text,
  p_initial_balance numeric
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_name text := trim(p_name);
  v_balance numeric(14, 2) := round(coalesce(p_initial_balance, 0)::numeric, 2);
  v_member_id bigint;
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  if v_name is null or char_length(v_name) = 0 or char_length(v_name) > 60 then
    raise exception 'Member name must be between 1 and 60 characters';
  end if;

  if not exists (
    select 1
    from public.ledgers
    where id = p_ledger_id
      and deleted_at is null
  ) then
    raise exception 'Ledger does not exist';
  end if;

  insert into public.members(ledger_id, name, balance)
  values (p_ledger_id, v_name, v_balance)
  returning id into v_member_id;

  insert into public.transactions(
    ledger_id,
    member_id,
    member_name,
    amount,
    balance_before,
    balance_after,
    note,
    operator_id
  ) values (
    p_ledger_id,
    v_member_id,
    v_name,
    v_balance,
    0,
    v_balance,
    '初始余额',
    (select auth.uid())
  );

  return v_member_id;
end;
$$;

create or replace function public.adjust_balance(
  p_member_id bigint,
  p_amount numeric,
  p_note text default null
)
returns numeric
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_ledger_id bigint;
  v_member_name text;
  v_before numeric(14, 2);
  v_amount numeric(14, 2) := round(p_amount::numeric, 2);
  v_after numeric(14, 2);
  v_note text := nullif(trim(p_note), '');
begin
  if not private.is_admin() then
    raise exception 'Only administrators can perform this operation';
  end if;

  if v_amount is null or v_amount = 0 then
    raise exception 'Amount must be a non-zero number';
  end if;

  if v_note is not null and char_length(v_note) > 200 then
    raise exception 'Note must be 200 characters or fewer';
  end if;

  select m.ledger_id, m.name, m.balance
  into v_ledger_id, v_member_name, v_before
  from public.members as m
  join public.ledgers as l on l.id = m.ledger_id
  where m.id = p_member_id
    and l.deleted_at is null
  for update of m;

  if not found then
    raise exception 'Member does not exist';
  end if;

  v_after := v_before + v_amount;

  update public.members
  set balance = v_after
  where id = p_member_id;

  insert into public.transactions(
    ledger_id,
    member_id,
    member_name,
    amount,
    balance_before,
    balance_after,
    note,
    operator_id
  ) values (
    v_ledger_id,
    p_member_id,
    v_member_name,
    v_amount,
    v_before,
    v_after,
    v_note,
    (select auth.uid())
  );

  return v_after;
end;
$$;

-- ============================================================
-- Data API privileges (RLS still decides which rows are allowed)
-- ============================================================

revoke all on table public.admins from anon, authenticated;
revoke all on table public.ledgers from anon, authenticated;
revoke all on table public.members from anon, authenticated;
revoke all on table public.transactions from anon, authenticated;

-- A signed-in user can only see their own row because of the admins RLS policy.
grant select on table public.admins to authenticated;

-- These permissions are needed by SECURITY INVOKER RPC functions and reads.
-- RLS blocks every non-admin account from ledger data.
grant select, insert, update on table public.ledgers to authenticated;
grant select, insert, update on table public.members to authenticated;
grant select, insert on table public.transactions to authenticated;

-- Identity columns use PostgreSQL sequences. SECURITY INVOKER RPCs need sequence usage.
grant usage, select on all sequences in schema public to authenticated;

revoke execute on function public.create_ledger(text) from public, anon;
revoke execute on function public.delete_ledger(bigint) from public, anon;
revoke execute on function public.add_member(bigint, text, numeric) from public, anon;
revoke execute on function public.adjust_balance(bigint, numeric, text) from public, anon;

grant execute on function public.create_ledger(text) to authenticated;
grant execute on function public.delete_ledger(bigint) to authenticated;
grant execute on function public.add_member(bigint, text, numeric) to authenticated;
grant execute on function public.adjust_balance(bigint, numeric, text) to authenticated;

commit;

-- ============================================================
-- AFTER running this schema:
-- 1. Create a user in Supabase Dashboard -> Authentication -> Users.
-- 2. Copy that user's UUID.
-- 3. Run the following separately, replacing the UUID:
--
-- insert into public.admins(user_id)
-- values ('00000000-0000-0000-0000-000000000000');
-- ============================================================
